sudo: required
language: node_js

node_js:
- '8'

script:
- npm test

deploy:
  provider: npm
  email: oss@findmypast.com
  api_key: $NPM_TOKEN
  on:
    tags: true
    repo: findmypast-oss/eslint-config-findmypast
